# Generated by Django 4.1.7 on 2023-03-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='detail',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
