# Generated by Django 4.1.7 on 2023-03-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_alter_cart_stuffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='stuffs',
            field=models.ManyToManyField(blank=True, null=True, to='mall.stuff'),
        ),
    ]
