# Generated by Django 4.1.7 on 2023-04-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0006_stuff_quantity_alter_cart_stuffs"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuff",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="stuff_img"),
        ),
    ]
