# Generated by Django 4.1.7 on 2023-04-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0007_stuff_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="stuff",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 1, 11, 21, 57, 688333, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
