# Generated by Django 4.1.7 on 2023-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0008_stuff_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuff", name="pub_date", field=models.DateTimeField(),
        ),
    ]
