# Generated by Django 4.1.7 on 2023-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0009_alter_stuff_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="quantity", field=models.JSONField(default="{}"),
        ),
    ]
