# Generated by Django 4.1.7 on 2023-04-02 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0012_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart", name="quantity", field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(model_name="cart", name="stuffs",),
        migrations.AddField(
            model_name="cart",
            name="stuffs",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="mall.stuff"
            ),
            preserve_default=False,
        ),
    ]
