# Generated by Django 4.1.7 on 2023-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0013_alter_cart_quantity_remove_cart_stuffs_cart_stuffs"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="checked", field=models.BooleanField(default=False),
        ),
    ]
