# Generated by Django 4.1.7 on 2023-04-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0015_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="total", field=models.IntegerField(default=0),
        ),
    ]
