# Generated by Django 4.1.7 on 2023-04-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0017_alter_order_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mall.cart"
            ),
        ),
    ]
