# Generated by Django 4.1.7 on 2023-04-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0018_alter_order_list"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="checked",),
    ]
