# Generated by Django 4.1.7 on 2023-04-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mall", "0021_alter_order_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mall.cart"
            ),
        ),
    ]
